### ISSUE TITLE
Adapta theme.

### ISSUE THREAD

**Issue by lebarondemerde** [tsujan/Kvantum#146]
Hi,

Could you consider creating matching themes for [Adapta](https://github.com/adapta-project/adapta-gtk-theme)?

Thank you!

**Comment by tsujan** [comment]
As for "could", yes! As for the time needed for that, I'm currently very busy with other projects, especially LXQt. So, it's just a matter of finding some free time.

**Comment by lebarondemerde** [comment]
LXQt is certainly more relevant than a specific theme. 👍

Thank you! 👍

**Comment by tsujan** [comment]
You're welcome!

I'll ask you to test it whenever I make the first version of "KvAdapta".

**Comment by tsujan** [comment]
I started to make it little by little. It needs a few small modifications to Kvantum, so it might take a while, but so far so good:

![kvadapta](https://user-images.githubusercontent.com/981076/29448078-2de3903c-840a-11e7-93f1-9e9a2a2655fe.png)

**Comment by lebarondemerde** [comment]
Nice! Thanks for your work and time.

There is also a [request](https://github.com/adapta-project/adapta-gtk-theme/issues/304) on Adapta for a KDE theme.

**Comment by tsujan** [comment]
> There is also a request on Adapta for a KDE theme.

Some plasma theme matching it should be possible but KDE is too focused on Breeze and Breeze is so elementary: you can't even change the color of its window decoration, let alone make it translucent. In the above screenshot, I've used Emerald with [Compiz](https://github.com/compiz-reloaded) under LXQt.

**Comment by tsujan** [comment]
`KvAdapta` is now included in and depends on the latest git Kvantum (which comes with lots of subtle fixes). It matches and is inspired by the Adapta GTK theme but isn't a clone of it.

I'm not fond of flat themes with sharp corners but I like this one; maybe because of its uncomplicated look :) Moreover, it revealed several tiny bugs, which are fixed now. Thanks for the idea!

Although I'm using `KvAdapta`, I'd be very grateful if you test it and tell me if you encounter any problem.

Please also note that the Breeze titlebar isn't suitable for this theme. I use Aurorae (can't include it in Kvantum) or Emerald+Compiz but have added an Openbox theme.

Will make a dark variant (KvAdaptaDark) later.

**Comment by tsujan** [comment]
If you test it, please note that all toolbar/menubar texts should be readable, like in this screenshot (Audacious-qt5):

![kvadapta-final](https://user-images.githubusercontent.com/981076/29654597-0f1c5b9e-88c3-11e7-89f5-495a0928764b.png)

**Comment by lebarondemerde** [comment]
Hi! That was pretty fast.

I will update to "master" today and test it.
The titlebar is not a issue for me since a I use bspwm/i3, without them.

Thanks million!

**Comment by lebarondemerde** [comment]
Hi!

It seem to be working fine*: https://ibb.co/d6NSGk

The only problem I had was indeed updating the FreeBSD port to use master still does not include KvAdapta, I downloaded it manually. I shall investigate that...

* for some reason github is having issues with the image.

**Comment by tsujan** [comment]
Thanks for the feedback! Please note that KvAdapta needs the latest Kvantum; with an older version, you might see weird things ;)

> for some reason github is having issues with the image.

Strange! I've never encountered that. Maybe it's because of the browser. It should be OK with Firefox, Chromium and QupZilla (if identified as Firefox).

I leave this tracker open until I make KvAdaptaDark.

**Comment by lebarondemerde** [comment]
I built using the last commit ( 392d098 ).

I am using Firefox, however heavily [tweaked](https://github.com/pyllyukko/user.js). One of those tweaks could be breaking something.

Thanks!

**Comment by ceyhunnabiyev** [comment]
Hi @tsujan , 
What about Adapta dark variant, eta variant and button ripple effect? Any plan for these?

**Comment by tsujan** [comment]
@ceyhunnabiyev I'll make a dark variant as soon as I have less life problems and more free time -- that's the reason why I haven't closed this tracker yet. Please also note that KvAdapta is not a clone of Adapta but matches it pretty well.

I have no plan to make an "eta" variant. Actually, I don't like copying GTK themes in Kvantum. Yes, I've done so for a few well-known GTK themes and might do it again in future but my preferred themes are those that are more original (like KvCurves3d, KvFlatLight, KvSimplicity,...). However, I pay attention to users' preferences too.

Kvantum has state-change and transient scrollbar animations but no  "ripple effect". I don't have a plan to add one yet but who knows what might happen in future?  ;)

**Comment by tsujan** [comment]
@lebarondemerde I've noticed that you use FreeBSD; don't you? I'd be very grateful if you report any problem Kvantum may have on BSD systems because I don't have one. Thanks in advance!

**Comment by ceyhunnabiyev** [comment]
@tsujan, thanks for your answer, but most of themes has variant for small resolution(laptops).

**Comment by tsujan** [comment]
@ceyhunnabiyev I tested Adapta-eta right now and saw no difference except for smaller sizes. That's a piece of cake in Kvatum but I really don't think it's worth adding three kinds of Adapta, one of which just with smaller sizes.

How important is it to you? What's the resolution of your laptop's monitor.

**Comment by tsujan** [comment]
Moreover, I think KvAdapta is already "eta" because I haven't used the large sizes of Adapta in it.

**Comment by ceyhunnabiyev** [comment]
@tsujan , Ok , no problem. Thanks for Great  Work .

**Comment by tsujan** [comment]
You're welcome! I checked again: KvAdapta is really "eta" ;) I don't like themes that waste the space too much.

**Comment by ceyhunnabiyev** [comment]
I pleasantly wait dark variant..

**Comment by lebarondemerde** [comment]
@tsujan 

Yes, I am on FreeBSD. No problems here so far, however I am an i3/bspwm user and so I do not have too many graphic programs. I mean I may miss some detail eventually.

About the KvAdapta variants, since the differences seem to be just some theme "scaling", eventually it could be added into the "Configure Active Theme" section, if possible.

Thanks!

**Comment by tsujan** [comment]
@lebarondemerde Good to know that Kvantum has no problem on FreeBSD :) I had FreeBSD on VirtualBox but lost its virtual hard.

> eventually it could be added into the "Configure Active Theme" section

Kvantum Manager includes only those keys that usually don't ruin the look of a theme when changed. Frame sizes and margins aren't safe to change in this regard.

Anyhow, as I said above, most of the themes that come with Kvantum don't wast the available space and, in that sense, are "eta".

**Comment by varlesh** [comment]
I modify :)
![image](https://user-images.githubusercontent.com/8083855/30319687-8e6bcea4-97c1-11e7-8c5c-f1e522736122.png)

**Comment by tsujan** [comment]
You made a titlebar? It's nice.

**Comment by varlesh** [comment]
Yes :)
I try made plasma theme (if it possible, because buttons rendered very specific on plasmashell)

**Comment by tsujan** [comment]
Recently, I was completing the "inactive" state in Kvantum (which is like the "fallback" mode in GTK) and might add some "inactiveness"  to KvAdapta.

**Comment by tsujan** [comment]
@varlesh Why are the toolbar *normal* icons pale in you screenshot (which is elegant, BTW)? Does it have something to do with your icon theme?

**Comment by varlesh** [comment]
No, it's kvantum draw colors for icons. Papirus use another colors.
I'm upload theme later... when finish all

**Comment by tsujan** [comment]
How is that possible?! Except for selection tinting, I put no code for coloring icons in Kvantum. It should be KDE. Here, under LXQt, all toolbar (symbolic) icons are white.

I'm very curious to know how that happens.

**Comment by tsujan** [comment]
Found the cause: when `text.normal.color` under [Toolbar] is the same as `window.text.color`, those icons are colored accordingly.

However, that color isn't appropriate for window texts, IMO.

**Comment by tsujan** [comment]
A short explanation about why it's impossible to set the color of symbolic icons in the style plugin:

Both KDE and LXQt use the *application* window text color for symbolic icons when their background is near the window color and use the inverse of that color (plus a highlight tint) when the background has a high contrast with the window color. If they used the *widget's* window text color, there would be a way to color symbolic icons in Kvantum. However, the icon engine knows nothing about widgets; hence it can only use the *application* window text color.

**Comment by varlesh** [comment]
@tsujan It's possible use shadow hint for toolbar widget?
![image](https://user-images.githubusercontent.com/8083855/30360753-3b516b18-9864-11e7-80f1-03d21c387d42.png)
I'm enlarge bottom area and change color to window plus add shadow, but  it's not good looking with konsole:
![image](https://user-images.githubusercontent.com/8083855/30360809-a12594c8-9864-11e7-8d1e-bb8bb51b4049.png)
Also if bottom ID change to transparent and add shadow, anyway used window background...

**Comment by tsujan** [comment]
No, shadow doesn't have any meaning for toolbars. That shadow-like part is just toolbar's bottom element. The window background is always for the whole window, including its toolbar.

Konsole's look is related to Konsole itself. For example, if its background was light, it would look differently. You don't need to worry about specific apps like Konsole.

**Comment by tsujan** [comment]
BTW, if you increase toolbar bottom frame size -- as you did above -- the extra size will be added in all directions -- top, right and left too. Toolbar is an exception in this regard.

**Comment by varlesh** [comment]
Ok... 
i'm refused from this idea, not good looking

**Comment by tsujan** [comment]
GTK large gaps and borders don't look good in GTK either, IMO. They waste some space too. Ubuntu has had a better idea with its theme called Ambiance. Contrary to most GTK themes, Ambiance doesn't waste space.

**Comment by varlesh** [comment]
yes with global menu Unity very comphortable for small screens

**Comment by varlesh** [comment]
@tsujan https://github.com/PapirusDevelopmentTeam/adapta-kde
Now only aurorae & kvantum... Later i try make plasma theme

**Comment by varlesh** [comment]
preview:
![image](https://user-images.githubusercontent.com/8083855/30369251-e165585a-9884-11e7-8986-02e09cb9bc37.png)

**Comment by varlesh** [comment]
My bold fonts shit on nvidia... i know this :)
.Xresources:
```
Xft.dpi:       96
Xft.antialias: true
Xft.hinting:   true
Xft.autohint:  false
Xft.hintstyle: hintslight
Xft.lcdfilter: lcddefault
Xft.rgba:      rgb
```
But bold font anyway looking ugly

**Comment by tsujan** [comment]
Good but, IMHO, the toolbar bottom frame size is too big, which cases all of its frame sizes -- and also those of menubar  (because menubar and toolbar are merged together) -- become too big. I think that thick shadow on the bottom isn't worth those big frames.. but tastes differ.

**Comment by varlesh** [comment]
I'm not solve this... maybe remove shadow or not. Need think about that.

**Comment by tsujan** [comment]
Qt doesn't allow different top and bottom frame sizes for toolbars; hence the big toolbar+menubar in your screennshot.

**Comment by tsujan** [comment]
@varlesh If you like that thick shadow under the toolbar in you Adapta version, you could set `merge_menubar_with_toolbar` to `false` and handle the menubar separately in it.

**Comment by tsujan** [comment]
Added KvAdaptaDark (might modify it later). Also added yet another workaround for bad app design (like in Kate).

I think any decoration made for KvAdapta should work with KvAdaptaDark too.

I close this but please add comments here if there's any problem.

@varlesh If you put your Kvantum themes inside GTK folders, you could put the dark variants alongside the light ones inside the light folder -- actually, you could always do so, with or without GTK. For example, if you make a modified version of KvAdaptaDark, you could put its SVG and kvconfig file in the theme folder of KvAdapta. This is a new feature and, although I've tested it, it may need more tests. Of course, your users should have a relatively recent git Kvantum for that to work.

**Comment by tsujan** [comment]
I've added the following info to the doc but I repeat it here with an example:

Supposing that your active Kvantum is KvAdapta, you could call the dark variant, KvAdaptaDark, by running an app with:
```
APP -style kvantum-dark
```
Or with exporting the environment variable first:
```
export QT_STYLE_OVERRIDE=kvantum-dark
APP
```

This might bee useful in GTK DEs.

**Comment by tsujan** [comment]
With KvAdapta, some apps (terminal, video playes,...) can be assigned to KvAdpataDark by Kvantum Manager. The result looks nice:

![adapta-dark](https://user-images.githubusercontent.com/981076/30484123-a020f1ea-9a3e-11e7-9855-de07df06757f.png)
